[project]
name = "imc-prosperity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "nbformat>=5.10.4",
    "orjson>=3.11.8",
    "pip>=26.1",
    "streamlit>=1.56.0",
    "typer>=0.25.0",
]
